# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapcachexmlgenerator.ui'
#
# Created: Tue Mar 17 19:47:35 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapcacheXmlGenerator(object):
    def setupUi(self, MapcacheXmlGenerator):
        MapcacheXmlGenerator.setObjectName(_fromUtf8("MapcacheXmlGenerator"))
        MapcacheXmlGenerator.resize(731, 631)
        MapcacheXmlGenerator.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(MapcacheXmlGenerator)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(MapcacheXmlGenerator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 1, 1, 1)
        self.txtCacheLayout_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheLayout_2.setObjectName(_fromUtf8("txtCacheLayout_2"))
        self.gridLayout_3.addWidget(self.txtCacheLayout_2, 6, 2, 1, 1)
        self.txtXmlConfigFilePath = QtGui.QLineEdit(self.tab)
        self.txtXmlConfigFilePath.setText(_fromUtf8(""))
        self.txtXmlConfigFilePath.setObjectName(_fromUtf8("txtXmlConfigFilePath"))
        self.gridLayout_3.addWidget(self.txtXmlConfigFilePath, 0, 2, 1, 1)
        self.txtCacheTemplate_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheTemplate_1.setObjectName(_fromUtf8("txtCacheTemplate_1"))
        self.gridLayout_3.addWidget(self.txtCacheTemplate_1, 2, 4, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 7, 3, 1, 1)
        self.txtCacheTemplate_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheTemplate_3.setObjectName(_fromUtf8("txtCacheTemplate_3"))
        self.gridLayout_3.addWidget(self.txtCacheTemplate_3, 10, 4, 1, 1)
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 9, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 1, 1, 1)
        self.txtCacheHost_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheHost_3.setObjectName(_fromUtf8("txtCacheHost_3"))
        self.gridLayout_3.addWidget(self.txtCacheHost_3, 11, 4, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 5, 3, 1, 1)
        self.label_200 = QtGui.QLabel(self.tab)
        self.label_200.setObjectName(_fromUtf8("label_200"))
        self.gridLayout_3.addWidget(self.label_200, 13, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 6, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.tab)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_3.addWidget(self.label_42, 14, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_3.addWidget(self.label_33, 9, 3, 1, 1)
        self.label_43 = QtGui.QLabel(self.tab)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 15, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 5, 1, 1, 1)
        self.txtCacheDbfile_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheDbfile_2.setObjectName(_fromUtf8("txtCacheDbfile_2"))
        self.gridLayout_3.addWidget(self.txtCacheDbfile_2, 8, 4, 1, 1)
        self.txtCacheDbfile_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheDbfile_1.setObjectName(_fromUtf8("txtCacheDbfile_1"))
        self.gridLayout_3.addWidget(self.txtCacheDbfile_1, 4, 4, 1, 1)
        self.txtCacheType_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheType_4.setObjectName(_fromUtf8("txtCacheType_4"))
        self.gridLayout_3.addWidget(self.txtCacheType_4, 13, 4, 1, 1)
        self.txtCachePort_1 = QtGui.QLineEdit(self.tab)
        self.txtCachePort_1.setObjectName(_fromUtf8("txtCachePort_1"))
        self.gridLayout_3.addWidget(self.txtCachePort_1, 4, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 6, 1, 1, 1)
        self.txtCacheType_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheType_1.setObjectName(_fromUtf8("txtCacheType_1"))
        self.gridLayout_3.addWidget(self.txtCacheType_1, 1, 4, 1, 1)
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_3.addWidget(self.label_32, 9, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.tab)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_3.addWidget(self.label_44, 14, 3, 1, 1)
        self.txtCacheLayout_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheLayout_4.setObjectName(_fromUtf8("txtCacheLayout_4"))
        self.gridLayout_3.addWidget(self.txtCacheLayout_4, 14, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_3.addWidget(self.label_40, 13, 3, 1, 1)
        self.label_38 = QtGui.QLabel(self.tab)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_3.addWidget(self.label_38, 12, 3, 1, 1)
        self.label_47 = QtGui.QLabel(self.tab)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_3.addWidget(self.label_47, 8, 1, 1, 1)
        self.label_45 = QtGui.QLabel(self.tab)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_3.addWidget(self.label_45, 15, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.tab)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_3.addWidget(self.label_46, 16, 3, 1, 1)
        self.txtCacheTemplate_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheTemplate_2.setObjectName(_fromUtf8("txtCacheTemplate_2"))
        self.gridLayout_3.addWidget(self.txtCacheTemplate_2, 6, 4, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 8, 3, 1, 1)
        self.txtCacheDbfile_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheDbfile_4.setObjectName(_fromUtf8("txtCacheDbfile_4"))
        self.gridLayout_3.addWidget(self.txtCacheDbfile_4, 16, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.txtCacheType_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheType_2.setObjectName(_fromUtf8("txtCacheType_2"))
        self.gridLayout_3.addWidget(self.txtCacheType_2, 5, 4, 1, 1)
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_3.addWidget(self.label_35, 10, 3, 1, 1)
        self.txtCacheLayout_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheLayout_3.setObjectName(_fromUtf8("txtCacheLayout_3"))
        self.gridLayout_3.addWidget(self.txtCacheLayout_3, 10, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_3.addWidget(self.label_39, 13, 1, 1, 1)
        self.txtCacheHost_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheHost_2.setObjectName(_fromUtf8("txtCacheHost_2"))
        self.gridLayout_3.addWidget(self.txtCacheHost_2, 7, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 3, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 7, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.tab)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_3.addWidget(self.label_37, 11, 3, 1, 1)
        self.txtCacheBase_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheBase_2.setObjectName(_fromUtf8("txtCacheBase_2"))
        self.gridLayout_3.addWidget(self.txtCacheBase_2, 7, 2, 1, 1)
        self.txtCacheName_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheName_4.setObjectName(_fromUtf8("txtCacheName_4"))
        self.gridLayout_3.addWidget(self.txtCacheName_4, 13, 2, 1, 1)
        self.port = QtGui.QLabel(self.tab)
        self.port.setObjectName(_fromUtf8("port"))
        self.gridLayout_3.addWidget(self.port, 4, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 3, 1, 1)
        self.txtCacheBase_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheBase_4.setObjectName(_fromUtf8("txtCacheBase_4"))
        self.gridLayout_3.addWidget(self.txtCacheBase_4, 15, 2, 1, 1)
        self.txtCacheBase_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheBase_3.setObjectName(_fromUtf8("txtCacheBase_3"))
        self.gridLayout_3.addWidget(self.txtCacheBase_3, 11, 2, 1, 1)
        self.txtCacheTemplate_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheTemplate_4.setObjectName(_fromUtf8("txtCacheTemplate_4"))
        self.gridLayout_3.addWidget(self.txtCacheTemplate_4, 14, 4, 1, 1)
        self.txtCacheHost_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheHost_1.setObjectName(_fromUtf8("txtCacheHost_1"))
        self.gridLayout_3.addWidget(self.txtCacheHost_1, 3, 4, 1, 1)
        self.txtCacheName_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheName_3.setObjectName(_fromUtf8("txtCacheName_3"))
        self.gridLayout_3.addWidget(self.txtCacheName_3, 9, 2, 1, 1)
        self.txtCacheName_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheName_1.setText(_fromUtf8(""))
        self.txtCacheName_1.setObjectName(_fromUtf8("txtCacheName_1"))
        self.gridLayout_3.addWidget(self.txtCacheName_1, 1, 2, 1, 1)
        self.txtCacheLayout_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheLayout_1.setObjectName(_fromUtf8("txtCacheLayout_1"))
        self.gridLayout_3.addWidget(self.txtCacheLayout_1, 2, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 10, 1, 1, 1)
        self.txtCacheType_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheType_3.setObjectName(_fromUtf8("txtCacheType_3"))
        self.gridLayout_3.addWidget(self.txtCacheType_3, 9, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 3, 1, 1)
        self.txtCacheBase_1 = QtGui.QLineEdit(self.tab)
        self.txtCacheBase_1.setObjectName(_fromUtf8("txtCacheBase_1"))
        self.gridLayout_3.addWidget(self.txtCacheBase_1, 3, 2, 1, 1)
        self.txtCacheHost_4 = QtGui.QLineEdit(self.tab)
        self.txtCacheHost_4.setObjectName(_fromUtf8("txtCacheHost_4"))
        self.gridLayout_3.addWidget(self.txtCacheHost_4, 15, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.tab)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_3.addWidget(self.label_36, 11, 1, 1, 1)
        self.txtCacheName_2 = QtGui.QLineEdit(self.tab)
        self.txtCacheName_2.setObjectName(_fromUtf8("txtCacheName_2"))
        self.gridLayout_3.addWidget(self.txtCacheName_2, 5, 2, 1, 1)
        self.btnChooseFile = QtGui.QToolButton(self.tab)
        self.btnChooseFile.setObjectName(_fromUtf8("btnChooseFile"))
        self.gridLayout_3.addWidget(self.btnChooseFile, 0, 3, 1, 1)
        self.txtCacheDbfile_3 = QtGui.QLineEdit(self.tab)
        self.txtCacheDbfile_3.setObjectName(_fromUtf8("txtCacheDbfile_3"))
        self.gridLayout_3.addWidget(self.txtCacheDbfile_3, 12, 4, 1, 1)
        self.txtCachePort_2 = QtGui.QLineEdit(self.tab)
        self.txtCachePort_2.setObjectName(_fromUtf8("txtCachePort_2"))
        self.gridLayout_3.addWidget(self.txtCachePort_2, 8, 2, 1, 1)
        self.label_48 = QtGui.QLabel(self.tab)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_3.addWidget(self.label_48, 12, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.tab)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_3.addWidget(self.label_49, 16, 1, 1, 1)
        self.txtCachePort_3 = QtGui.QLineEdit(self.tab)
        self.txtCachePort_3.setObjectName(_fromUtf8("txtCachePort_3"))
        self.gridLayout_3.addWidget(self.txtCachePort_3, 12, 2, 1, 1)
        self.txtCachePort_4 = QtGui.QLineEdit(self.tab)
        self.txtCachePort_4.setObjectName(_fromUtf8("txtCachePort_4"))
        self.gridLayout_3.addWidget(self.txtCachePort_4, 16, 2, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtSourceFormat_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceFormat_3.setObjectName(_fromUtf8("txtSourceFormat_3"))
        self.gridLayout_7.addWidget(self.txtSourceFormat_3, 9, 2, 1, 1)
        self.label_54 = QtGui.QLabel(self.tab_2)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_7.addWidget(self.label_54, 5, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.tab_2)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_7.addWidget(self.label_63, 8, 3, 1, 1)
        self.label_202 = QtGui.QLabel(self.tab_2)
        self.label_202.setObjectName(_fromUtf8("label_202"))
        self.gridLayout_7.addWidget(self.label_202, 8, 1, 1, 1)
        self.label_69 = QtGui.QLabel(self.tab_2)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_7.addWidget(self.label_69, 12, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.tab_2)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_7.addWidget(self.label_58, 5, 3, 1, 1)
        self.txtSourceType_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceType_3.setObjectName(_fromUtf8("txtSourceType_3"))
        self.gridLayout_7.addWidget(self.txtSourceType_3, 8, 4, 1, 1)
        self.txtSourceName_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceName_2.setObjectName(_fromUtf8("txtSourceName_2"))
        self.gridLayout_7.addWidget(self.txtSourceName_2, 4, 2, 1, 1)
        self.label_65 = QtGui.QLabel(self.tab_2)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_7.addWidget(self.label_65, 9, 3, 1, 1)
        self.label_62 = QtGui.QLabel(self.tab_2)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_7.addWidget(self.label_62, 8, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.tab_2)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_7.addWidget(self.label_70, 13, 1, 1, 1)
        self.label_57 = QtGui.QLabel(self.tab_2)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_7.addWidget(self.label_57, 4, 3, 1, 1)
        self.label_53 = QtGui.QLabel(self.tab_2)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_7.addWidget(self.label_53, 4, 1, 1, 1)
        self.label_52 = QtGui.QLabel(self.tab_2)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_7.addWidget(self.label_52, 0, 0, 1, 1)
        self.txtSourceFormat_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceFormat_1.setObjectName(_fromUtf8("txtSourceFormat_1"))
        self.gridLayout_7.addWidget(self.txtSourceFormat_1, 1, 2, 1, 1)
        self.txtSourceType_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceType_1.setObjectName(_fromUtf8("txtSourceType_1"))
        self.gridLayout_7.addWidget(self.txtSourceType_1, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.txtSourceLayer_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceLayer_1.setObjectName(_fromUtf8("txtSourceLayer_1"))
        self.gridLayout_7.addWidget(self.txtSourceLayer_1, 1, 4, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 3, 1, 1)
        self.txtSourceName_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceName_1.setObjectName(_fromUtf8("txtSourceName_1"))
        self.gridLayout_7.addWidget(self.txtSourceName_1, 0, 2, 1, 1)
        self.label_60 = QtGui.QLabel(self.tab_2)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_7.addWidget(self.label_60, 4, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.tab_2)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_7.addWidget(self.label_64, 9, 1, 1, 1)
        self.txtSourceName_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceName_3.setObjectName(_fromUtf8("txtSourceName_3"))
        self.gridLayout_7.addWidget(self.txtSourceName_3, 8, 2, 1, 1)
        self.txtSourceLayer_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceLayer_2.setObjectName(_fromUtf8("txtSourceLayer_2"))
        self.gridLayout_7.addWidget(self.txtSourceLayer_2, 5, 4, 1, 1)
        self.txtSourceType_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceType_2.setObjectName(_fromUtf8("txtSourceType_2"))
        self.gridLayout_7.addWidget(self.txtSourceType_2, 4, 4, 1, 1)
        self.txtSourceFormat_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceFormat_2.setObjectName(_fromUtf8("txtSourceFormat_2"))
        self.gridLayout_7.addWidget(self.txtSourceFormat_2, 5, 2, 1, 1)
        self.txtSourceLayer_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceLayer_3.setObjectName(_fromUtf8("txtSourceLayer_3"))
        self.gridLayout_7.addWidget(self.txtSourceLayer_3, 9, 4, 1, 1)
        self.label_73 = QtGui.QLabel(self.tab_2)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_7.addWidget(self.label_73, 12, 0, 1, 1)
        self.label_74 = QtGui.QLabel(self.tab_2)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_7.addWidget(self.label_74, 12, 3, 1, 1)
        self.label_75 = QtGui.QLabel(self.tab_2)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_7.addWidget(self.label_75, 13, 3, 1, 1)
        self.txtSourceName_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceName_4.setObjectName(_fromUtf8("txtSourceName_4"))
        self.gridLayout_7.addWidget(self.txtSourceName_4, 12, 2, 1, 1)
        self.txtSourceType_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceType_4.setObjectName(_fromUtf8("txtSourceType_4"))
        self.gridLayout_7.addWidget(self.txtSourceType_4, 12, 4, 1, 1)
        self.txtSourceFormat_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceFormat_4.setObjectName(_fromUtf8("txtSourceFormat_4"))
        self.gridLayout_7.addWidget(self.txtSourceFormat_4, 13, 2, 1, 1)
        self.txtSourceLayer_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceLayer_4.setObjectName(_fromUtf8("txtSourceLayer_4"))
        self.gridLayout_7.addWidget(self.txtSourceLayer_4, 13, 4, 1, 1)
        self.txtSourceConnectionTimeout_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceConnectionTimeout_1.setObjectName(_fromUtf8("txtSourceConnectionTimeout_1"))
        self.gridLayout_7.addWidget(self.txtSourceConnectionTimeout_1, 3, 4, 1, 1)
        self.label_201 = QtGui.QLabel(self.tab_2)
        self.label_201.setObjectName(_fromUtf8("label_201"))
        self.gridLayout_7.addWidget(self.label_201, 3, 3, 1, 1)
        self.label_50 = QtGui.QLabel(self.tab_2)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_7.addWidget(self.label_50, 3, 1, 1, 1)
        self.txtSourceReferer_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceReferer_1.setObjectName(_fromUtf8("txtSourceReferer_1"))
        self.gridLayout_7.addWidget(self.txtSourceReferer_1, 3, 2, 1, 1)
        self.txtSourceUserAgent_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUserAgent_1.setObjectName(_fromUtf8("txtSourceUserAgent_1"))
        self.gridLayout_7.addWidget(self.txtSourceUserAgent_1, 2, 4, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 2, 3, 1, 1)
        self.txtSourceConnectionTimeout_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceConnectionTimeout_2.setObjectName(_fromUtf8("txtSourceConnectionTimeout_2"))
        self.gridLayout_7.addWidget(self.txtSourceConnectionTimeout_2, 7, 4, 1, 1)
        self.label_56 = QtGui.QLabel(self.tab_2)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_7.addWidget(self.label_56, 7, 3, 1, 1)
        self.txtSourceReferer_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceReferer_2.setObjectName(_fromUtf8("txtSourceReferer_2"))
        self.gridLayout_7.addWidget(self.txtSourceReferer_2, 7, 2, 1, 1)
        self.label_59 = QtGui.QLabel(self.tab_2)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_7.addWidget(self.label_59, 7, 1, 1, 1)
        self.txtSourceUserAgent_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUserAgent_2.setObjectName(_fromUtf8("txtSourceUserAgent_2"))
        self.gridLayout_7.addWidget(self.txtSourceUserAgent_2, 6, 4, 1, 1)
        self.label_55 = QtGui.QLabel(self.tab_2)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_7.addWidget(self.label_55, 6, 3, 1, 1)
        self.txtSourceConnectionTimeout_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceConnectionTimeout_3.setObjectName(_fromUtf8("txtSourceConnectionTimeout_3"))
        self.gridLayout_7.addWidget(self.txtSourceConnectionTimeout_3, 11, 4, 1, 1)
        self.label_68 = QtGui.QLabel(self.tab_2)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_7.addWidget(self.label_68, 11, 3, 1, 1)
        self.label_67 = QtGui.QLabel(self.tab_2)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_7.addWidget(self.label_67, 11, 1, 1, 1)
        self.txtSourceReferer_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceReferer_3.setObjectName(_fromUtf8("txtSourceReferer_3"))
        self.gridLayout_7.addWidget(self.txtSourceReferer_3, 11, 2, 1, 1)
        self.txtSourceUserAgent_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUserAgent_3.setObjectName(_fromUtf8("txtSourceUserAgent_3"))
        self.gridLayout_7.addWidget(self.txtSourceUserAgent_3, 10, 4, 1, 1)
        self.label_66 = QtGui.QLabel(self.tab_2)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_7.addWidget(self.label_66, 10, 3, 1, 1)
        self.txtSourceConnectionTimeout_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceConnectionTimeout_4.setObjectName(_fromUtf8("txtSourceConnectionTimeout_4"))
        self.gridLayout_7.addWidget(self.txtSourceConnectionTimeout_4, 15, 4, 1, 1)
        self.label_72 = QtGui.QLabel(self.tab_2)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_7.addWidget(self.label_72, 15, 3, 1, 1)
        self.label_76 = QtGui.QLabel(self.tab_2)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_7.addWidget(self.label_76, 15, 1, 1, 1)
        self.txtSourceReferer_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceReferer_4.setObjectName(_fromUtf8("txtSourceReferer_4"))
        self.gridLayout_7.addWidget(self.txtSourceReferer_4, 15, 2, 1, 1)
        self.txtSourceUserAgent_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUserAgent_4.setObjectName(_fromUtf8("txtSourceUserAgent_4"))
        self.gridLayout_7.addWidget(self.txtSourceUserAgent_4, 14, 4, 1, 1)
        self.label_71 = QtGui.QLabel(self.tab_2)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_7.addWidget(self.label_71, 14, 3, 1, 1)
        self.txtSourceUrl_1 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUrl_1.setObjectName(_fromUtf8("txtSourceUrl_1"))
        self.gridLayout_7.addWidget(self.txtSourceUrl_1, 2, 2, 1, 1)
        self.label_223 = QtGui.QLabel(self.tab_2)
        self.label_223.setObjectName(_fromUtf8("label_223"))
        self.gridLayout_7.addWidget(self.label_223, 6, 1, 1, 1)
        self.label_224 = QtGui.QLabel(self.tab_2)
        self.label_224.setObjectName(_fromUtf8("label_224"))
        self.gridLayout_7.addWidget(self.label_224, 10, 1, 1, 1)
        self.label_128 = QtGui.QLabel(self.tab_2)
        self.label_128.setObjectName(_fromUtf8("label_128"))
        self.gridLayout_7.addWidget(self.label_128, 14, 1, 1, 1)
        self.txtSourceUrl_2 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUrl_2.setObjectName(_fromUtf8("txtSourceUrl_2"))
        self.gridLayout_7.addWidget(self.txtSourceUrl_2, 6, 2, 1, 1)
        self.txtSourceUrl_3 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUrl_3.setObjectName(_fromUtf8("txtSourceUrl_3"))
        self.gridLayout_7.addWidget(self.txtSourceUrl_3, 10, 2, 1, 1)
        self.txtSourceUrl_4 = QtGui.QLineEdit(self.tab_2)
        self.txtSourceUrl_4.setObjectName(_fromUtf8("txtSourceUrl_4"))
        self.gridLayout_7.addWidget(self.txtSourceUrl_4, 14, 2, 1, 1)
        self.label_222 = QtGui.QLabel(self.tab_2)
        self.label_222.setObjectName(_fromUtf8("label_222"))
        self.gridLayout_7.addWidget(self.label_222, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtTilesetName = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetName.setText(_fromUtf8(""))
        self.txtTilesetName.setObjectName(_fromUtf8("txtTilesetName"))
        self.gridLayout_8.addWidget(self.txtTilesetName, 3, 2, 1, 1)
        self.txtTilesetSource = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetSource.setText(_fromUtf8(""))
        self.txtTilesetSource.setObjectName(_fromUtf8("txtTilesetSource"))
        self.gridLayout_8.addWidget(self.txtTilesetSource, 3, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 3, 1, 1, 1)
        self.label_199 = QtGui.QLabel(self.tab_3)
        self.label_199.setObjectName(_fromUtf8("label_199"))
        self.gridLayout_8.addWidget(self.label_199, 3, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.tab_3)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_8.addWidget(self.label_81, 9, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 8, 1, 1, 1)
        self.txtTilesetGridText_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridText_2.setObjectName(_fromUtf8("txtTilesetGridText_2"))
        self.gridLayout_8.addWidget(self.txtTilesetGridText_2, 9, 2, 1, 1)
        self.txtTilesetGridMinzoom_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridMinzoom_2.setObjectName(_fromUtf8("txtTilesetGridMinzoom_2"))
        self.gridLayout_8.addWidget(self.txtTilesetGridMinzoom_2, 10, 2, 1, 1)
        self.txtTilesetMetadataTitle = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetMetadataTitle.setObjectName(_fromUtf8("txtTilesetMetadataTitle"))
        self.gridLayout_8.addWidget(self.txtTilesetMetadataTitle, 11, 2, 1, 1)
        self.label_84 = QtGui.QLabel(self.tab_3)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_8.addWidget(self.label_84, 11, 1, 1, 1)
        self.label_97 = QtGui.QLabel(self.tab_3)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.gridLayout_8.addWidget(self.label_97, 17, 1, 1, 1)
        self.label_100 = QtGui.QLabel(self.tab_3)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.gridLayout_8.addWidget(self.label_100, 18, 3, 1, 1)
        self.label_98 = QtGui.QLabel(self.tab_3)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout_8.addWidget(self.label_98, 18, 1, 1, 1)
        self.label_101 = QtGui.QLabel(self.tab_3)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_8.addWidget(self.label_101, 17, 0, 1, 1)
        self.label_92 = QtGui.QLabel(self.tab_3)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.gridLayout_8.addWidget(self.label_92, 15, 1, 1, 1)
        self.label_96 = QtGui.QLabel(self.tab_3)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_8.addWidget(self.label_96, 16, 3, 1, 1)
        self.txtTilesetDimensionName_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionName_1.setObjectName(_fromUtf8("txtTilesetDimensionName_1"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionName_1, 16, 2, 1, 1)
        self.label_102 = QtGui.QLabel(self.tab_3)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.gridLayout_8.addWidget(self.label_102, 19, 1, 1, 1)
        self.txtTilesetDimensionDefault_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionDefault_2.setObjectName(_fromUtf8("txtTilesetDimensionDefault_2"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionDefault_2, 18, 4, 1, 1)
        self.txtTilesetDimensionType_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionType_2.setObjectName(_fromUtf8("txtTilesetDimensionType_2"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionType_2, 17, 4, 1, 1)
        self.label_77 = QtGui.QLabel(self.tab_3)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_8.addWidget(self.label_77, 7, 0, 1, 1)
        self.label_86 = QtGui.QLabel(self.tab_3)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_8.addWidget(self.label_86, 11, 0, 1, 1)
        self.label_78 = QtGui.QLabel(self.tab_3)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_8.addWidget(self.label_78, 7, 1, 1, 1)
        self.label_82 = QtGui.QLabel(self.tab_3)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_8.addWidget(self.label_82, 10, 3, 1, 1)
        self.txtTilesetGridRestrictedExtent_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridRestrictedExtent_1.setObjectName(_fromUtf8("txtTilesetGridRestrictedExtent_1"))
        self.gridLayout_8.addWidget(self.txtTilesetGridRestrictedExtent_1, 7, 4, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 8, 3, 1, 1)
        self.txtTilesetDimensionText_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionText_1.setObjectName(_fromUtf8("txtTilesetDimensionText_1"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionText_1, 15, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 7, 3, 1, 1)
        self.txtTilesetGridMaxzoom_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridMaxzoom_1.setObjectName(_fromUtf8("txtTilesetGridMaxzoom_1"))
        self.gridLayout_8.addWidget(self.txtTilesetGridMaxzoom_1, 8, 4, 1, 1)
        self.txtTilesetGridText_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridText_1.setObjectName(_fromUtf8("txtTilesetGridText_1"))
        self.gridLayout_8.addWidget(self.txtTilesetGridText_1, 7, 2, 1, 1)
        self.label_80 = QtGui.QLabel(self.tab_3)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_8.addWidget(self.label_80, 10, 1, 1, 1)
        self.txtTilesetGridMaxzoom_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridMaxzoom_2.setObjectName(_fromUtf8("txtTilesetGridMaxzoom_2"))
        self.gridLayout_8.addWidget(self.txtTilesetGridMaxzoom_2, 10, 4, 1, 1)
        self.txtTilesetGridRestrictedExtent_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridRestrictedExtent_2.setObjectName(_fromUtf8("txtTilesetGridRestrictedExtent_2"))
        self.gridLayout_8.addWidget(self.txtTilesetGridRestrictedExtent_2, 9, 4, 1, 1)
        self.label_85 = QtGui.QLabel(self.tab_3)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_8.addWidget(self.label_85, 11, 3, 1, 1)
        self.txtTilesetDimensionName_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionName_2.setObjectName(_fromUtf8("txtTilesetDimensionName_2"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionName_2, 18, 2, 1, 1)
        self.txtTilesetDimensionDefault_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionDefault_1.setObjectName(_fromUtf8("txtTilesetDimensionDefault_1"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionDefault_1, 16, 4, 1, 1)
        self.txtTilesetDimensionType_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionType_1.setObjectName(_fromUtf8("txtTilesetDimensionType_1"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionType_1, 15, 4, 1, 1)
        self.label_99 = QtGui.QLabel(self.tab_3)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout_8.addWidget(self.label_99, 17, 3, 1, 1)
        self.label_93 = QtGui.QLabel(self.tab_3)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_8.addWidget(self.label_93, 15, 3, 1, 1)
        self.label_94 = QtGui.QLabel(self.tab_3)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_8.addWidget(self.label_94, 15, 0, 1, 1)
        self.txtTilesetMetadataAbstract = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetMetadataAbstract.setObjectName(_fromUtf8("txtTilesetMetadataAbstract"))
        self.gridLayout_8.addWidget(self.txtTilesetMetadataAbstract, 11, 4, 1, 1)
        self.label_83 = QtGui.QLabel(self.tab_3)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_8.addWidget(self.label_83, 9, 0, 1, 1)
        self.label_79 = QtGui.QLabel(self.tab_3)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_8.addWidget(self.label_79, 9, 1, 1, 1)
        self.txtTilesetGridMinzoom_1 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetGridMinzoom_1.setObjectName(_fromUtf8("txtTilesetGridMinzoom_1"))
        self.gridLayout_8.addWidget(self.txtTilesetGridMinzoom_1, 8, 2, 1, 1)
        self.txtTilesetDimensionText_2 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionText_2.setObjectName(_fromUtf8("txtTilesetDimensionText_2"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionText_2, 17, 2, 1, 1)
        self.label_95 = QtGui.QLabel(self.tab_3)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.gridLayout_8.addWidget(self.label_95, 16, 1, 1, 1)
        self.label_103 = QtGui.QLabel(self.tab_3)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout_8.addWidget(self.label_103, 20, 1, 1, 1)
        self.label_104 = QtGui.QLabel(self.tab_3)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout_8.addWidget(self.label_104, 19, 0, 1, 1)
        self.label_105 = QtGui.QLabel(self.tab_3)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout_8.addWidget(self.label_105, 19, 3, 1, 1)
        self.label_106 = QtGui.QLabel(self.tab_3)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout_8.addWidget(self.label_106, 20, 3, 1, 1)
        self.txtTilesetDimensionText_3 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionText_3.setObjectName(_fromUtf8("txtTilesetDimensionText_3"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionText_3, 19, 2, 1, 1)
        self.txtTilesetDimensionName_3 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionName_3.setObjectName(_fromUtf8("txtTilesetDimensionName_3"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionName_3, 20, 2, 1, 1)
        self.txtTilesetDimensionType_3 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionType_3.setObjectName(_fromUtf8("txtTilesetDimensionType_3"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionType_3, 19, 4, 1, 1)
        self.txtTilesetDimensionDefault_3 = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetDimensionDefault_3.setObjectName(_fromUtf8("txtTilesetDimensionDefault_3"))
        self.gridLayout_8.addWidget(self.txtTilesetDimensionDefault_3, 20, 4, 1, 1)
        self.txtTilesetFormat = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetFormat.setObjectName(_fromUtf8("txtTilesetFormat"))
        self.gridLayout_8.addWidget(self.txtTilesetFormat, 4, 4, 1, 1)
        self.label_89 = QtGui.QLabel(self.tab_3)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_8.addWidget(self.label_89, 5, 3, 1, 1)
        self.txtTilesetMetatile = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetMetatile.setObjectName(_fromUtf8("txtTilesetMetatile"))
        self.gridLayout_8.addWidget(self.txtTilesetMetatile, 5, 2, 1, 1)
        self.txtTilesetCache = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetCache.setObjectName(_fromUtf8("txtTilesetCache"))
        self.gridLayout_8.addWidget(self.txtTilesetCache, 4, 2, 1, 1)
        self.label_88 = QtGui.QLabel(self.tab_3)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.gridLayout_8.addWidget(self.label_88, 5, 1, 1, 1)
        self.label_87 = QtGui.QLabel(self.tab_3)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_8.addWidget(self.label_87, 4, 3, 1, 1)
        self.txtTilesetMetabuffer = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetMetabuffer.setObjectName(_fromUtf8("txtTilesetMetabuffer"))
        self.gridLayout_8.addWidget(self.txtTilesetMetabuffer, 5, 4, 1, 1)
        self.label_129 = QtGui.QLabel(self.tab_3)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.gridLayout_8.addWidget(self.label_129, 4, 1, 1, 1)
        self.label_90 = QtGui.QLabel(self.tab_3)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_8.addWidget(self.label_90, 6, 1, 1, 1)
        self.txtTilesetExpires = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetExpires.setObjectName(_fromUtf8("txtTilesetExpires"))
        self.gridLayout_8.addWidget(self.txtTilesetExpires, 6, 2, 1, 1)
        self.label_91 = QtGui.QLabel(self.tab_3)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_8.addWidget(self.label_91, 6, 3, 1, 1)
        self.txtTilesetAutoExpire = QtGui.QLineEdit(self.tab_3)
        self.txtTilesetAutoExpire.setObjectName(_fromUtf8("txtTilesetAutoExpire"))
        self.gridLayout_8.addWidget(self.txtTilesetAutoExpire, 6, 4, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.label_118 = QtGui.QLabel(self.tab_4)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.gridLayout_31.addWidget(self.label_118, 7, 1, 1, 1)
        self.txtServiceEnabled_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_1.setText(_fromUtf8(""))
        self.txtServiceEnabled_1.setObjectName(_fromUtf8("txtServiceEnabled_1"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_1, 0, 4, 1, 1)
        self.txtServiceResampleMode_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceResampleMode_1.setText(_fromUtf8(""))
        self.txtServiceResampleMode_1.setObjectName(_fromUtf8("txtServiceResampleMode_1"))
        self.gridLayout_31.addWidget(self.txtServiceResampleMode_1, 1, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_31.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_31.addWidget(self.label_4, 0, 1, 1, 1)
        self.txtTinyowsLogLevel = QtGui.QLabel(self.tab_4)
        self.txtTinyowsLogLevel.setObjectName(_fromUtf8("txtTinyowsLogLevel"))
        self.gridLayout_31.addWidget(self.txtTinyowsLogLevel, 1, 3, 1, 1)
        self.txtServiceFullWms_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceFullWms_1.setText(_fromUtf8(""))
        self.txtServiceFullWms_1.setObjectName(_fromUtf8("txtServiceFullWms_1"))
        self.gridLayout_31.addWidget(self.txtServiceFullWms_1, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_31.addWidget(self.label_5, 0, 3, 1, 1)
        self.txtServiceType_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_1.setText(_fromUtf8(""))
        self.txtServiceType_1.setObjectName(_fromUtf8("txtServiceType_1"))
        self.gridLayout_31.addWidget(self.txtServiceType_1, 0, 2, 1, 1)
        self.txtServiceType_4 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_4.setObjectName(_fromUtf8("txtServiceType_4"))
        self.gridLayout_31.addWidget(self.txtServiceType_4, 5, 2, 1, 1)
        self.label_125 = QtGui.QLabel(self.tab_4)
        self.label_125.setObjectName(_fromUtf8("label_125"))
        self.gridLayout_31.addWidget(self.label_125, 7, 3, 1, 1)
        self.txtServiceEnabled_5 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_5.setObjectName(_fromUtf8("txtServiceEnabled_5"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_5, 6, 4, 1, 1)
        self.txtServiceEnabled_3 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_3.setObjectName(_fromUtf8("txtServiceEnabled_3"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_3, 4, 4, 1, 1)
        self.txtServiceType_7 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_7.setObjectName(_fromUtf8("txtServiceType_7"))
        self.gridLayout_31.addWidget(self.txtServiceType_7, 8, 2, 1, 1)
        self.txtServiceFormat_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceFormat_1.setObjectName(_fromUtf8("txtServiceFormat_1"))
        self.gridLayout_31.addWidget(self.txtServiceFormat_1, 2, 2, 1, 1)
        self.label_121 = QtGui.QLabel(self.tab_4)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout_31.addWidget(self.label_121, 3, 3, 1, 1)
        self.label_116 = QtGui.QLabel(self.tab_4)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.gridLayout_31.addWidget(self.label_116, 4, 1, 1, 1)
        self.label_110 = QtGui.QLabel(self.tab_4)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout_31.addWidget(self.label_110, 3, 1, 1, 1)
        self.txtServiceEnabled_2 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_2.setObjectName(_fromUtf8("txtServiceEnabled_2"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_2, 3, 4, 1, 1)
        self.label_114 = QtGui.QLabel(self.tab_4)
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.gridLayout_31.addWidget(self.label_114, 7, 0, 1, 1)
        self.label_113 = QtGui.QLabel(self.tab_4)
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.gridLayout_31.addWidget(self.label_113, 6, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_31.addWidget(self.label_21, 0, 0, 1, 1)
        self.txtServiceType_6 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_6.setObjectName(_fromUtf8("txtServiceType_6"))
        self.gridLayout_31.addWidget(self.txtServiceType_6, 7, 2, 1, 1)
        self.txtServiceEnabled_6 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_6.setObjectName(_fromUtf8("txtServiceEnabled_6"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_6, 7, 4, 1, 1)
        self.txtServiceEnabled_7 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_7.setObjectName(_fromUtf8("txtServiceEnabled_7"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_7, 8, 4, 1, 1)
        self.label_124 = QtGui.QLabel(self.tab_4)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.gridLayout_31.addWidget(self.label_124, 6, 3, 1, 1)
        self.label_123 = QtGui.QLabel(self.tab_4)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout_31.addWidget(self.label_123, 5, 3, 1, 1)
        self.label_115 = QtGui.QLabel(self.tab_4)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.gridLayout_31.addWidget(self.label_115, 8, 0, 1, 1)
        self.label_120 = QtGui.QLabel(self.tab_4)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.gridLayout_31.addWidget(self.label_120, 8, 1, 1, 1)
        self.label_108 = QtGui.QLabel(self.tab_4)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout_31.addWidget(self.label_108, 2, 3, 1, 1)
        self.label_119 = QtGui.QLabel(self.tab_4)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.gridLayout_31.addWidget(self.label_119, 6, 1, 1, 1)
        self.label_109 = QtGui.QLabel(self.tab_4)
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout_31.addWidget(self.label_109, 3, 0, 1, 1)
        self.txtServiceEnabled_4 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceEnabled_4.setObjectName(_fromUtf8("txtServiceEnabled_4"))
        self.gridLayout_31.addWidget(self.txtServiceEnabled_4, 5, 4, 1, 1)
        self.label_117 = QtGui.QLabel(self.tab_4)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout_31.addWidget(self.label_117, 5, 1, 1, 1)
        self.label_126 = QtGui.QLabel(self.tab_4)
        self.label_126.setObjectName(_fromUtf8("label_126"))
        self.gridLayout_31.addWidget(self.label_126, 8, 3, 1, 1)
        self.label_107 = QtGui.QLabel(self.tab_4)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout_31.addWidget(self.label_107, 2, 1, 1, 1)
        self.label_111 = QtGui.QLabel(self.tab_4)
        self.label_111.setObjectName(_fromUtf8("label_111"))
        self.gridLayout_31.addWidget(self.label_111, 4, 0, 1, 1)
        self.txtServiceType_2 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_2.setObjectName(_fromUtf8("txtServiceType_2"))
        self.gridLayout_31.addWidget(self.txtServiceType_2, 3, 2, 1, 1)
        self.label_112 = QtGui.QLabel(self.tab_4)
        self.label_112.setObjectName(_fromUtf8("label_112"))
        self.gridLayout_31.addWidget(self.label_112, 5, 0, 1, 1)
        self.txtServiceMaxsize_1 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceMaxsize_1.setObjectName(_fromUtf8("txtServiceMaxsize_1"))
        self.gridLayout_31.addWidget(self.txtServiceMaxsize_1, 2, 4, 1, 1)
        self.txtServiceType_5 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_5.setObjectName(_fromUtf8("txtServiceType_5"))
        self.gridLayout_31.addWidget(self.txtServiceType_5, 6, 2, 1, 1)
        self.txtServiceType_3 = QtGui.QLineEdit(self.tab_4)
        self.txtServiceType_3.setObjectName(_fromUtf8("txtServiceType_3"))
        self.gridLayout_31.addWidget(self.txtServiceType_3, 4, 2, 1, 1)
        self.label_122 = QtGui.QLabel(self.tab_4)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout_31.addWidget(self.label_122, 4, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_31.addItem(spacerItem, 9, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_32 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.txtGridExtent = QtGui.QLineEdit(self.tab_6)
        self.txtGridExtent.setText(_fromUtf8(""))
        self.txtGridExtent.setObjectName(_fromUtf8("txtGridExtent"))
        self.gridLayout_32.addWidget(self.txtGridExtent, 0, 4, 1, 1)
        self.label_51 = QtGui.QLabel(self.tab_6)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_32.addWidget(self.label_51, 0, 3, 1, 1)
        self.txtGridUnits = QtGui.QLineEdit(self.tab_6)
        self.txtGridUnits.setText(_fromUtf8(""))
        self.txtGridUnits.setObjectName(_fromUtf8("txtGridUnits"))
        self.gridLayout_32.addWidget(self.txtGridUnits, 1, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 350, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem1, 4, 2, 1, 1)
        self.txtTinyowsLogLevel1 = QtGui.QLabel(self.tab_6)
        self.txtTinyowsLogLevel1.setObjectName(_fromUtf8("txtTinyowsLogLevel1"))
        self.gridLayout_32.addWidget(self.txtTinyowsLogLevel1, 1, 3, 1, 1)
        self.txtGridSize = QtGui.QLineEdit(self.tab_6)
        self.txtGridSize.setText(_fromUtf8(""))
        self.txtGridSize.setObjectName(_fromUtf8("txtGridSize"))
        self.gridLayout_32.addWidget(self.txtGridSize, 1, 2, 1, 1)
        self.label_130 = QtGui.QLabel(self.tab_6)
        self.label_130.setObjectName(_fromUtf8("label_130"))
        self.gridLayout_32.addWidget(self.label_130, 3, 1, 1, 1)
        self.label_61 = QtGui.QLabel(self.tab_6)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_32.addWidget(self.label_61, 2, 1, 1, 1)
        self.txtGridTitle = QtGui.QLineEdit(self.tab_6)
        self.txtGridTitle.setObjectName(_fromUtf8("txtGridTitle"))
        self.gridLayout_32.addWidget(self.txtGridTitle, 3, 2, 1, 1)
        self.label_131 = QtGui.QLabel(self.tab_6)
        self.label_131.setObjectName(_fromUtf8("label_131"))
        self.gridLayout_32.addWidget(self.label_131, 3, 0, 1, 1)
        self.txtGridWellKnownScaleSet = QtGui.QLineEdit(self.tab_6)
        self.txtGridWellKnownScaleSet.setObjectName(_fromUtf8("txtGridWellKnownScaleSet"))
        self.gridLayout_32.addWidget(self.txtGridWellKnownScaleSet, 3, 4, 1, 1)
        self.txtGridSrs = QtGui.QLineEdit(self.tab_6)
        self.txtGridSrs.setText(_fromUtf8(""))
        self.txtGridSrs.setObjectName(_fromUtf8("txtGridSrs"))
        self.gridLayout_32.addWidget(self.txtGridSrs, 2, 2, 1, 1)
        self.label_127 = QtGui.QLabel(self.tab_6)
        self.label_127.setObjectName(_fromUtf8("label_127"))
        self.gridLayout_32.addWidget(self.label_127, 2, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_6)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_32.addWidget(self.label_41, 1, 1, 1, 1)
        self.label_132 = QtGui.QLabel(self.tab_6)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.gridLayout_32.addWidget(self.label_132, 3, 3, 1, 1)
        self.txtGridResolution = QtGui.QLineEdit(self.tab_6)
        self.txtGridResolution.setObjectName(_fromUtf8("txtGridResolution"))
        self.gridLayout_32.addWidget(self.txtGridResolution, 2, 4, 1, 1)
        self.label_133 = QtGui.QLabel(self.tab_6)
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.gridLayout_32.addWidget(self.label_133, 0, 1, 1, 1)
        self.txtGridName = QtGui.QLineEdit(self.tab_6)
        self.txtGridName.setObjectName(_fromUtf8("txtGridName"))
        self.gridLayout_32.addWidget(self.txtGridName, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(MapcacheXmlGenerator)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.label.setBuddy(self.txtXmlConfigFilePath)

        self.retranslateUi(MapcacheXmlGenerator)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MapcacheXmlGenerator.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MapcacheXmlGenerator.accept)
        QtCore.QMetaObject.connectSlotsByName(MapcacheXmlGenerator)
        MapcacheXmlGenerator.setTabOrder(self.txtXmlConfigFilePath, self.txtCacheName_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheName_1, self.txtCacheType_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheType_1, self.txtCacheLayout_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheLayout_1, self.txtCacheTemplate_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheTemplate_1, self.txtCacheBase_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheBase_1, self.txtCacheHost_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheHost_1, self.txtCachePort_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCachePort_1, self.txtCacheDbfile_1)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheDbfile_1, self.txtCacheName_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheName_2, self.txtCacheType_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheType_2, self.txtCacheLayout_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheLayout_2, self.txtCacheTemplate_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheTemplate_2, self.txtCacheBase_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheBase_2, self.txtCacheHost_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheHost_2, self.txtCachePort_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCachePort_2, self.txtCacheDbfile_2)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheDbfile_2, self.txtCacheName_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheName_3, self.txtCacheType_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheType_3, self.txtCacheLayout_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheLayout_3, self.txtCacheTemplate_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheTemplate_3, self.txtCacheBase_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheBase_3, self.txtCacheHost_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheHost_3, self.txtCachePort_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCachePort_3, self.txtCacheDbfile_3)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheDbfile_3, self.txtCacheName_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheName_4, self.txtCacheType_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheType_4, self.txtCacheLayout_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheLayout_4, self.txtCacheTemplate_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheTemplate_4, self.txtCacheBase_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheBase_4, self.txtCacheHost_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheHost_4, self.txtCachePort_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCachePort_4, self.txtCacheDbfile_4)
        MapcacheXmlGenerator.setTabOrder(self.txtCacheDbfile_4, self.txtSourceName_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceName_1, self.txtSourceType_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceType_1, self.txtSourceFormat_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceFormat_1, self.txtSourceLayer_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceLayer_1, self.txtSourceUrl_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUrl_1, self.txtSourceUserAgent_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUserAgent_1, self.txtSourceReferer_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceReferer_1, self.txtSourceConnectionTimeout_1)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceConnectionTimeout_1, self.txtSourceName_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceName_2, self.txtSourceType_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceType_2, self.txtSourceFormat_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceFormat_2, self.txtSourceLayer_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceLayer_2, self.txtSourceUrl_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUrl_2, self.txtSourceUserAgent_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUserAgent_2, self.txtSourceReferer_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceReferer_2, self.txtSourceConnectionTimeout_2)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceConnectionTimeout_2, self.txtSourceName_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceName_3, self.txtSourceType_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceType_3, self.txtSourceFormat_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceFormat_3, self.txtSourceLayer_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceLayer_3, self.txtSourceUrl_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUrl_3, self.txtSourceUserAgent_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUserAgent_3, self.txtSourceReferer_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceReferer_3, self.txtSourceConnectionTimeout_3)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceConnectionTimeout_3, self.txtSourceName_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceName_4, self.txtSourceType_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceType_4, self.txtSourceFormat_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceFormat_4, self.txtSourceLayer_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceLayer_4, self.txtSourceUrl_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUrl_4, self.txtSourceUserAgent_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceUserAgent_4, self.txtSourceReferer_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceReferer_4, self.txtSourceConnectionTimeout_4)
        MapcacheXmlGenerator.setTabOrder(self.txtSourceConnectionTimeout_4, self.txtTilesetName)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetName, self.txtTilesetSource)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetSource, self.txtTilesetCache)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetCache, self.txtTilesetFormat)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetFormat, self.txtTilesetMetatile)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetMetatile, self.txtTilesetMetabuffer)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetMetabuffer, self.txtTilesetExpires)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetExpires, self.txtTilesetAutoExpire)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetAutoExpire, self.txtTilesetGridText_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridText_1, self.txtTilesetGridRestrictedExtent_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridRestrictedExtent_1, self.txtTilesetGridMinzoom_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridMinzoom_1, self.txtTilesetGridMaxzoom_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridMaxzoom_1, self.txtTilesetGridText_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridText_2, self.txtTilesetGridRestrictedExtent_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridRestrictedExtent_2, self.txtTilesetGridMinzoom_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridMinzoom_2, self.txtTilesetGridMaxzoom_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetGridMaxzoom_2, self.txtTilesetMetadataTitle)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetMetadataTitle, self.txtTilesetMetadataAbstract)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetMetadataAbstract, self.txtTilesetDimensionText_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionText_1, self.txtTilesetDimensionType_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionType_1, self.txtTilesetDimensionName_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionName_1, self.txtTilesetDimensionDefault_1)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionDefault_1, self.txtTilesetDimensionText_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionText_2, self.txtTilesetDimensionType_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionType_2, self.txtTilesetDimensionName_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionName_2, self.txtTilesetDimensionDefault_2)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionDefault_2, self.txtTilesetDimensionText_3)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionText_3, self.txtTilesetDimensionType_3)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionType_3, self.txtTilesetDimensionName_3)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionName_3, self.txtTilesetDimensionDefault_3)
        MapcacheXmlGenerator.setTabOrder(self.txtTilesetDimensionDefault_3, self.txtServiceType_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_1, self.txtServiceEnabled_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_1, self.txtServiceFullWms_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceFullWms_1, self.txtServiceResampleMode_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceResampleMode_1, self.txtServiceFormat_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceFormat_1, self.txtServiceMaxsize_1)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceMaxsize_1, self.txtServiceType_2)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_2, self.txtServiceEnabled_2)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_2, self.txtServiceType_3)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_3, self.txtServiceEnabled_3)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_3, self.txtServiceType_4)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_4, self.txtServiceEnabled_4)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_4, self.txtServiceType_5)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_5, self.txtServiceEnabled_5)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_5, self.txtServiceType_6)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_6, self.txtServiceEnabled_6)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_6, self.txtServiceType_7)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceType_7, self.txtServiceEnabled_7)
        MapcacheXmlGenerator.setTabOrder(self.txtServiceEnabled_7, self.txtGridName)
        MapcacheXmlGenerator.setTabOrder(self.txtGridName, self.txtGridExtent)
        MapcacheXmlGenerator.setTabOrder(self.txtGridExtent, self.txtGridSize)
        MapcacheXmlGenerator.setTabOrder(self.txtGridSize, self.txtGridUnits)
        MapcacheXmlGenerator.setTabOrder(self.txtGridUnits, self.txtGridSrs)
        MapcacheXmlGenerator.setTabOrder(self.txtGridSrs, self.txtGridResolution)
        MapcacheXmlGenerator.setTabOrder(self.txtGridResolution, self.txtGridTitle)
        MapcacheXmlGenerator.setTabOrder(self.txtGridTitle, self.txtGridWellKnownScaleSet)
        MapcacheXmlGenerator.setTabOrder(self.txtGridWellKnownScaleSet, self.tabWidget)
        MapcacheXmlGenerator.setTabOrder(self.tabWidget, self.btnChooseFile)

    def retranslateUi(self, MapcacheXmlGenerator):
        MapcacheXmlGenerator.setWindowTitle(_translate("MapcacheXmlGenerator", "Mapcache XML Generator", None))
        self.label_12.setText(_translate("MapcacheXmlGenerator", "cache", None))
        self.label_10.setText(_translate("MapcacheXmlGenerator", "layout", None))
        self.txtXmlConfigFilePath.setToolTip(_translate("MapcacheXmlGenerator", "Name for the map file to be created from the QGIS project file", None))
        self.label_29.setText(_translate("MapcacheXmlGenerator", "host", None))
        self.label_31.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.label_13.setText(_translate("MapcacheXmlGenerator", "base", None))
        self.label_25.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_200.setText(_translate("MapcacheXmlGenerator", "cache", None))
        self.label_27.setText(_translate("MapcacheXmlGenerator", "template", None))
        self.label_19.setText(_translate("MapcacheXmlGenerator", "cache", None))
        self.label_42.setText(_translate("MapcacheXmlGenerator", "layout", None))
        self.label_33.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_43.setText(_translate("MapcacheXmlGenerator", "base", None))
        self.label_16.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.label_26.setText(_translate("MapcacheXmlGenerator", "layout", None))
        self.label_32.setText(_translate("MapcacheXmlGenerator", "cache", None))
        self.label_44.setText(_translate("MapcacheXmlGenerator", "template", None))
        self.label_40.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_38.setText(_translate("MapcacheXmlGenerator", "dbfile", None))
        self.label_47.setText(_translate("MapcacheXmlGenerator", "port", None))
        self.label_45.setText(_translate("MapcacheXmlGenerator", "host", None))
        self.label_46.setText(_translate("MapcacheXmlGenerator", "dbfile", None))
        self.label_30.setText(_translate("MapcacheXmlGenerator", "dbfile", None))
        self.label_8.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.label.setText(_translate("MapcacheXmlGenerator", "XML config file", None))
        self.label_35.setText(_translate("MapcacheXmlGenerator", "template", None))
        self.label_39.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.label_11.setText(_translate("MapcacheXmlGenerator", "template", None))
        self.label_14.setText(_translate("MapcacheXmlGenerator", "host", None))
        self.label_28.setText(_translate("MapcacheXmlGenerator", "base", None))
        self.label_37.setText(_translate("MapcacheXmlGenerator", "host", None))
        self.port.setText(_translate("MapcacheXmlGenerator", "port", None))
        self.label_15.setText(_translate("MapcacheXmlGenerator", "dbfile", None))
        self.label_34.setText(_translate("MapcacheXmlGenerator", "layout", None))
        self.label_9.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_36.setText(_translate("MapcacheXmlGenerator", "base", None))
        self.btnChooseFile.setText(_translate("MapcacheXmlGenerator", "...", None))
        self.label_48.setText(_translate("MapcacheXmlGenerator", "port", None))
        self.label_49.setText(_translate("MapcacheXmlGenerator", "port", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MapcacheXmlGenerator", "Cache", None))
        self.label_54.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_63.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_202.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_69.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_58.setText(_translate("MapcacheXmlGenerator", "layers", None))
        self.label_65.setText(_translate("MapcacheXmlGenerator", "layers", None))
        self.label_62.setText(_translate("MapcacheXmlGenerator", "source", None))
        self.label_70.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_57.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_53.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_52.setText(_translate("MapcacheXmlGenerator", "source", None))
        self.label_2.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.label_17.setText(_translate("MapcacheXmlGenerator", "layers", None))
        self.label_7.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_3.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_60.setText(_translate("MapcacheXmlGenerator", "source", None))
        self.label_64.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_73.setText(_translate("MapcacheXmlGenerator", "source", None))
        self.label_74.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_75.setText(_translate("MapcacheXmlGenerator", "layers", None))
        self.label_201.setText(_translate("MapcacheXmlGenerator", "connection_timeout", None))
        self.label_50.setText(_translate("MapcacheXmlGenerator", "Referer", None))
        self.label_18.setText(_translate("MapcacheXmlGenerator", "User-Agent", None))
        self.label_56.setText(_translate("MapcacheXmlGenerator", "connection_timeout", None))
        self.label_59.setText(_translate("MapcacheXmlGenerator", "Referer", None))
        self.label_55.setText(_translate("MapcacheXmlGenerator", "User-Agent", None))
        self.label_68.setText(_translate("MapcacheXmlGenerator", "connection_timeout", None))
        self.label_67.setText(_translate("MapcacheXmlGenerator", "Referer", None))
        self.label_66.setText(_translate("MapcacheXmlGenerator", "User-Agent", None))
        self.label_72.setText(_translate("MapcacheXmlGenerator", "connection_timeout", None))
        self.label_76.setText(_translate("MapcacheXmlGenerator", "Referer", None))
        self.label_71.setText(_translate("MapcacheXmlGenerator", "User-Agent", None))
        self.label_223.setText(_translate("MapcacheXmlGenerator", "url", None))
        self.label_224.setText(_translate("MapcacheXmlGenerator", "url", None))
        self.label_128.setText(_translate("MapcacheXmlGenerator", "url", None))
        self.label_222.setText(_translate("MapcacheXmlGenerator", "url", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MapcacheXmlGenerator", "Source", None))
        self.label_20.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_199.setText(_translate("MapcacheXmlGenerator", "source", None))
        self.label_81.setText(_translate("MapcacheXmlGenerator", "restricted_extent", None))
        self.label_23.setText(_translate("MapcacheXmlGenerator", "minzoom", None))
        self.label_84.setText(_translate("MapcacheXmlGenerator", "title", None))
        self.label_97.setText(_translate("MapcacheXmlGenerator", "text", None))
        self.label_100.setText(_translate("MapcacheXmlGenerator", "default", None))
        self.label_98.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_101.setText(_translate("MapcacheXmlGenerator", "dimension", None))
        self.label_92.setText(_translate("MapcacheXmlGenerator", "text", None))
        self.label_96.setText(_translate("MapcacheXmlGenerator", "default", None))
        self.label_102.setText(_translate("MapcacheXmlGenerator", "text", None))
        self.label_77.setText(_translate("MapcacheXmlGenerator", "grid", None))
        self.label_86.setText(_translate("MapcacheXmlGenerator", "metadata", None))
        self.label_78.setText(_translate("MapcacheXmlGenerator", "text", None))
        self.label_82.setText(_translate("MapcacheXmlGenerator", "maxzoom", None))
        self.label_24.setText(_translate("MapcacheXmlGenerator", "maxzoom", None))
        self.label_22.setText(_translate("MapcacheXmlGenerator", "restricted_extent", None))
        self.label_80.setText(_translate("MapcacheXmlGenerator", "minzoom", None))
        self.label_85.setText(_translate("MapcacheXmlGenerator", "abstract", None))
        self.label_99.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_93.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_94.setText(_translate("MapcacheXmlGenerator", "dimension", None))
        self.label_83.setText(_translate("MapcacheXmlGenerator", "grid", None))
        self.label_79.setText(_translate("MapcacheXmlGenerator", "text", None))
        self.label_95.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_103.setText(_translate("MapcacheXmlGenerator", "name", None))
        self.label_104.setText(_translate("MapcacheXmlGenerator", "dimension", None))
        self.label_105.setText(_translate("MapcacheXmlGenerator", "type", None))
        self.label_106.setText(_translate("MapcacheXmlGenerator", "default", None))
        self.label_89.setText(_translate("MapcacheXmlGenerator", "metabuffer", None))
        self.label_88.setText(_translate("MapcacheXmlGenerator", "metatile", None))
        self.label_87.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_129.setText(_translate("MapcacheXmlGenerator", "cache", None))
        self.label_90.setText(_translate("MapcacheXmlGenerator", "expires", None))
        self.label_91.setText(_translate("MapcacheXmlGenerator", "auto_expire", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MapcacheXmlGenerator", "Tileset", None))
        self.label_118.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_6.setText(_translate("MapcacheXmlGenerator", "full_wms", None))
        self.label_4.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.txtTinyowsLogLevel.setText(_translate("MapcacheXmlGenerator", "resample_mode", None))
        self.label_5.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_125.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_121.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_116.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_110.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_114.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_113.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_21.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_124.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_123.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_115.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_120.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_108.setText(_translate("MapcacheXmlGenerator", "maxsize", None))
        self.label_119.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_109.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_117.setText(_translate("MapcacheXmlGenerator", "type*", None))
        self.label_126.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.label_107.setText(_translate("MapcacheXmlGenerator", "format", None))
        self.label_111.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_112.setText(_translate("MapcacheXmlGenerator", "service", None))
        self.label_122.setText(_translate("MapcacheXmlGenerator", "enabled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MapcacheXmlGenerator", "Service", None))
        self.label_51.setText(_translate("MapcacheXmlGenerator", "extent", None))
        self.txtTinyowsLogLevel1.setText(_translate("MapcacheXmlGenerator", "units", None))
        self.label_130.setText(_translate("MapcacheXmlGenerator", "title*", None))
        self.label_61.setText(_translate("MapcacheXmlGenerator", "srs", None))
        self.label_131.setText(_translate("MapcacheXmlGenerator", "metadata", None))
        self.label_127.setText(_translate("MapcacheXmlGenerator", "resolutions", None))
        self.label_41.setText(_translate("MapcacheXmlGenerator", "size", None))
        self.label_132.setText(_translate("MapcacheXmlGenerator", "WellKnownScaleSet", None))
        self.label_133.setText(_translate("MapcacheXmlGenerator", "name*", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MapcacheXmlGenerator", "Grid", None))

